sudo: True

language: python

matrix:
  include:
    - python: 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest requests pandas decorator -y
  - source activate test
  - conda install -c conda-forge google-auth -y
  - pip install git+https://github.com/intake/filesystem_spec
  - pip install vcrpy fusepy google-auth-oauthlib

script:
  - GCSFS_RECORD_MODE=none py.test -vv  gcsfs

notifications:
  email: false
