name: gcsfs_test
channels:
  - conda-forge
dependencies:
  - python==3.11
  - aiohttp
  - crcmod
  - decorator
  - fsspec
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - google-cloud-core
  - google-cloud-storage
  - grpcio
  - pytest
  - pytest-timeout
  - pytest-asyncio
  - pytest-cov
  - pytest-subtests
  - requests
  - ujson
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
