name: gcsfs_test
channels:
  - conda-forge
dependencies:
  - aiohttp
  - crcmod
  - decorator
  - fsspec
  - fusepy<3
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - google-cloud-core
  - libfuse<3
  - pytest
  - pytest-timeout
  - requests
  - ujson
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
